image: 715859896688.dkr.ecr.us-east-1.amazonaws.com/pipeline-x86-python

include:
  - template: 'Workflows/Boon-Pipelines.gitlab-ci.yml'

variables:
  GIT_STRATEGY: none
  GIT_SSL_NO_VERIFY: "true"
  CLANG_FORMAT: clang-format
  REF_NAME: master
  SHELL: /bin/bash
  CI_DEBUG_SERVICES: "true"

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan gitlab.boonlogic.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - export PATH=~/.local/bin:$PATH

stages:
  - build
  - self-test
  - test

build:
  stage: build
  tags:
    - expert-docker
  script:
  - chmod -Rf 755 ci-root && rm -rf ci-root || true
  - git clone git@gitlab.boonlogic.com:development/builder.git ci-root
  - cd ci-root
  - git checkout ${CI_COMMIT_REF_NAME} || true
  - BRANCH=${CI_COMMIT_REF_NAME} make expert-python-sdk-env
  - make expert-python-sdk-build
  - pipelines/expert-api/create-expertv3-test-env pipeline
  artifacts:
    paths:
    - ci-root/
    reports:
      dotenv:
        - ci-root/pipeline.env

code-check:
  stage: self-test
  tags:
    - expert-docker
  script:
    - cd ci-root
    - make expert-python-sdk-code-check

test-expert-v3:
  stage: test
  tags:
    - expert-docker
  services:
    - name: 715859896688.dkr.ecr.us-east-1.amazonaws.com/expert-server:${EXPERT_TAG}
      alias: expertv3-pipeline
  variables:
    BOON_PRODUCT_ID: expert-swagger
    BOON_API_KEY: $BOON_API_KEY
    BOON_API_TENANT: $BOON_API_TENANT
  script:
    - cd ${CI_PROJECT_DIR}/ci-root/packages/expert-python-sdk/expert-python-sdk
    - export BOON_TEST_LICENSE_FILE=${CI_PROJECT_DIR}/ci-root/.BoonLogic.license
    - make test-pipeline
  coverage: '/TOTAL.*\s([.\d]+)%/'
  artifacts:
    paths:
    - ci-root/packages/expert-python-sdk/expert-python-sdk

