name: Publish SDK to PyPi
on:
  push:
    tags:
      - v*
  pull_request:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: python3 -m pip install --upgrade build && python3 -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
